# Generated by Django 5.0.2 on 2024-03-17 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_event_admin_user'),
        ('Main', '0005_event_venue_alter_event_duration'),
    ]

    operations = [
    ]
